#!/usr/bin/env python3
"""three_arm_plot.py — figure pipeline for the three-arm work-distribution sweep.

Reads  docs/publications/arxiv/paper2a/data/three_arm/summary.csv
Writes docs/publications/arxiv/paper2a/data/fig_three_arm.tex (pgfplots, two
panels matching fig_decision_latency.tex's style):

  (a) p99 job latency vs drift δ̄ at H = 0.5 — the staleness axis
  (b) idle-while-work-exists vs heterogeneity H at δ̄ = 0 — the misrouting axis

Seed-averaged; the underlying per-run rows stay in the CSV.
"""
from __future__ import annotations

import csv
import statistics as st
from collections import defaultdict
from pathlib import Path

DATA = Path("docs/publications/arxiv/paper2a/data")
SRC = DATA / "three_arm" / "summary.csv"
OUT = DATA / "fig_three_arm.tex"

STYLE = {
    "pull":   "mark=*, thick, green!60!black",
    "gossip": "mark=square*, thick, blue!70!black",
    "broker": "mark=triangle*, thick, red!70!black",
}

def main() -> None:
    cells: dict[tuple[str, float, float], list[dict]] = defaultdict(list)
    for r in csv.DictReader(open(SRC)):
        cells[(r["arm"], float(r["het"]), float(r["drift"]))].append(r)

    def mean(arm: str, het: float, drift: float, key: str) -> float:
        c = cells[(arm, het, drift)]
        assert c, (arm, het, drift)
        return st.mean(float(r[key]) for r in c)

    hets = sorted({k[1] for k in cells})
    drifts = sorted({k[2] for k in cells})

    def coords(arm: str, xs, fixed_het=None, fixed_drift=None, key="p99_ms") -> str:
        pts = []
        for x in xs:
            het = fixed_het if fixed_het is not None else x
            drift = fixed_drift if fixed_drift is not None else x
            pts.append(f"({x},{mean(arm, het, drift, key):.3f})")
        return " ".join(pts)

    panels = []
    # Panel (a): p99 vs drift at H=0.5
    a_plots = "\n".join(
        f"\\addplot[{STYLE[arm]}] coordinates {{ {coords(arm, drifts, fixed_het=0.5, key='p99_ms')} }};\n"
        f"\\addlegendentry{{{arm}}}"
        for arm in ("pull", "gossip", "broker")
    )
    panels.append(rf"""\begin{{semilogyaxis}}[
  width=0.46\textwidth, height=5.2cm,
  xlabel={{Drift $\bar\delta$ (relative speed change /s)}},
  ylabel={{p99 job latency (ms)}},
  xtick={{0,0.05,0.2}},
  legend pos=north west,
  legend style={{font=\scriptsize}},
  grid=both, major grid style={{gray!30}}, minor grid style={{gray!10}},
  title={{(a) Tail latency vs drift ($H=0.5$)}},
  title style={{font=\small}},
  name=plota,
]
{a_plots}
\end{{semilogyaxis}}""")

    # Panel (b): IWWE vs H at drift=0
    b_plots = "\n".join(
        f"\\addplot[{STYLE[arm]}] coordinates {{ {coords(arm, hets, fixed_drift=0.0, key='iwwe')} }};\n"
        f"\\addlegendentry{{{arm}}}"
        for arm in ("pull", "gossip", "broker")
    )
    panels.append(rf"""\begin{{axis}}[
  width=0.46\textwidth, height=5.2cm,
  at={{(plota.east)}}, anchor=west, xshift=1.4cm,
  xlabel={{Heterogeneity $H$ (CV of worker speeds)}},
  ylabel={{idle-while-work-exists (fraction)}},
  xtick={{0,0.25,0.5,1.0}},
  ymin=0,
  legend pos=north west,
  legend style={{font=\scriptsize}},
  grid=both, major grid style={{gray!30}}, minor grid style={{gray!10}},
  title={{(b) Wasted capacity vs heterogeneity ($\bar\delta=0$)}},
  title style={{font=\small}},
]
{b_plots}
\end{{axis}}""")

    body = "\n".join(panels)
    OUT.write_text(rf"""% Generated by examples/three_arm_plot.py from three_arm/summary.csv — do not edit.
\begin{{figure}}[t]
\centering
\begin{{tikzpicture}}
{body}
\end{{tikzpicture}}
\caption{{Three-arm work-distribution comparison ($N=20$, $\lambda=0.65\times$
capacity, 3 seeds per cell, least-outstanding-requests push baseline).
(a)~Drift makes any observed worker state stale: push-arm p99 grows
$\sim$4$\times$ from $\bar\delta=0$ to $0.2$/s while pull, which predicts
nothing, degrades only with the queueing itself. (b)~Capacity idle while
work waits: flat and small for pull at every $H$; the prediction arms waste
3--5$\times$ more even at $H=0$, where their only remaining error source is
the decision pipeline itself.}}
\label{{fig:three-arm}}
\end{{figure}}
""")
    print(f"wrote {OUT}")

if __name__ == "__main__":
    main()
